### PR TITLE
resolves #60 introduce off method to unbind an event

### LINKED ISSUE #60: Add an off method
Add an `off` method as a complement to the `on` method. I've come across situations in my plugins when I want to listen for deck events only at certain times. It would be nice if I could unregister an event handler. jQuery has an `off` method for this very purpose. I think Bespoke.js needs the same.

If I understand the code correctly, it seems that if you invoke the function that is returned from the `on` method, it unregisters the event.

```js
deck.on('activate', activate)();
```

However, this is a very bizarre API, IMO. I'd much rather have an explicit `off` method to call.

### PR DESCRIPTION
**Pull request by mojavelinux**
As it turns out, we can add this method without any additional lines of code (and only a slight increase in the gzipped version). The `on` method can reuse the `off` method when building the return value by leveraging `bind`.

### CODE REVIEW

**Comment by markdalgleish** [comment]
Looks great. Happy to merge this once the conflicts are resolved.

**Comment by mojavelinux** [comment]
I'll get right on it. Stay tuned!

**Comment by mojavelinux** [comment]
Rebase complete!

**Comment by mojavelinux** [comment]
:beers:

**Pull request merged**
